### ISSUE TITLE
Includes

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/TAMM#49]
The TAMM includes need refactored.  For example, as it stands now `work.hpp` includes `ops.hpp`, which includes `labeled_tensor.hpp`.  The problem is that `work.hpp` uses `labeled_tensor.hpp` and thus there is a cyclic inclusion of `labeled_tensor.hpp`. 

Ultimately, if I am only using say the `Tensor` class, it should suffice to only include `tamm/tensor.hpp`.  At the moment I can only seem to use the `Tensor` class if I include `tamm/labeled_tensor.hpp`.

**Comment by ajaypanyala** [comment]
Fixed!
