### ISSUE TITLE
Comparison/Hashing

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/TAMM#69]
In order to use TAMM tensors in the SDE we need them to be hashable and comparable. Specifically we need the tensors to be hashable by the the BPHash library and to have :

```
template<typename T, typename U>
bool Tensor<T>::operator==(const tamm::Tensor<U>& rhs);
```
defined (or a free function version).

Implementing these functions requires knowledge of the internals of the tensors and is best done within the TAMM library.

**Comment by ajaypanyala** [comment]
Completed!
